version: '3.9'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: tenderhack_pass
      POSTGRES_USER: tenderhack_user
      POSTGRES_DB: tenderhack_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./temp_pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
