// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tenderhack.Core.Data.TenderhackDbContext;

#nullable disable

namespace Tenderhack.Core.Migrations.Tenderhack
{
    [DbContext(typeof(TenderhackDbContext))]
    [Migration("20210925141021_Tenderhack_Initial")]
    partial class Tenderhack_Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0-rc.1.21452.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Characteristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId");

                    b.HasIndex("Name");

                    b.HasIndex("Value");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConclusionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int?>("ProviderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PublicAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConclusionAt");

                    b.HasIndex("CustomerId");

                    b.HasIndex("Number");

                    b.HasIndex("Price");

                    b.HasIndex("ProviderId");

                    b.HasIndex("PublicAt");

                    b.ToTable("Contracts");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ContractId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProductId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("Amount");

                    b.HasIndex("ContractId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Quantity");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Inn")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<string>("Kpp")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)");

                    b.HasKey("Id");

                    b.HasIndex("Kpp");

                    b.HasIndex("Name");

                    b.HasIndex("Inn", "Kpp");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("CpgzCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("character varying(511)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CpgzCode");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.ProductsCharacteristics", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("CharacteristicId")
                        .HasColumnType("integer");

                    b.HasKey("ProductId", "CharacteristicId");

                    b.HasIndex("CharacteristicId");

                    b.ToTable("ProductsCharacteristics", (string)null);
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Contract", b =>
                {
                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Organization", "Customer")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Organization", "Provider")
                        .WithMany("SaleHistory")
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Customer");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Order", b =>
                {
                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Contract", "Contract")
                        .WithMany("Orders")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Contract");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Product", b =>
                {
                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.ProductsCharacteristics", b =>
                {
                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Characteristic", "Characteristic")
                        .WithMany("ProductsCharacteristics")
                        .HasForeignKey("CharacteristicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tenderhack.Core.Data.TenderhackDbContext.Models.Product", "Product")
                        .WithMany("ProductsCharacteristics")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Characteristic");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Characteristic", b =>
                {
                    b.Navigation("ProductsCharacteristics");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Contract", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Organization", b =>
                {
                    b.Navigation("PurchaseHistory");

                    b.Navigation("SaleHistory");
                });

            modelBuilder.Entity("Tenderhack.Core.Data.TenderhackDbContext.Models.Product", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductsCharacteristics");
                });
#pragma warning restore 612, 618
        }
    }
}
